notebook:
  container_name: 'jupyter-notebook'

  build: .

  ports:
    - '8888:8888'

  volumes:
    - ./Clients:/home/jovyan/work/Clients
    - ./Private:/home/jovyan/work/Private
    - ./Public:/home/jovyan/work/Public
